
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nauzetaduen
 */
public class MainFrame extends javax.swing.JFrame {
    private int currentTotalStats = 75;
    private final int MAX_STATS = 225;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePanel = new javax.swing.JPanel();
        templateLabel = new javax.swing.JLabel();
        templateTextField = new javax.swing.JTextField();
        skillsPanel = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        combo3 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        combo6 = new javax.swing.JComboBox<>();
        combo5 = new javax.swing.JComboBox<>();
        combo4 = new javax.swing.JComboBox<>();
        combo7 = new javax.swing.JComboBox<>();
        statsPanel = new javax.swing.JPanel();
        intLabel = new javax.swing.JLabel();
        intSlider = new javax.swing.JSlider();
        intTextField = new javax.swing.JTextField();
        strLabel = new javax.swing.JLabel();
        strSlider = new javax.swing.JSlider();
        strTextField = new javax.swing.JTextField();
        dexLabel = new javax.swing.JLabel();
        dexSlider = new javax.swing.JSlider();
        dexTextField = new javax.swing.JTextField();
        toogleInt = new javax.swing.JToggleButton();
        toogleStr = new javax.swing.JToggleButton();
        toogleDex = new javax.swing.JToggleButton();
        totalLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        separatorMenuItems = new javax.swing.JPopupMenu.Separator();
        deleteMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        whoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        templateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        templateLabel.setText("Template's Name:");

        templateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(templateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(templateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(templateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(templateLabel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        skillsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Skills"));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        combo6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        combo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        combo7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alchemy", "Anatomy", "Animal Lore", "Animal Taming", "Archery", "Arms Lore", "Begging", "Blacksmithy", "Bowcraft/Fletching", "Camping", "Carpentry", "Cartography", "Cooking", "Detecting Hidden", "Discordance", "Evaluating Inteligence", "Fencing", "Fishing", "Forensic Evaluation", "Healing", "Herding", "Hiding", "Inscription", "Item Identification", "Lockpicking", "Lumberjacking", "Mace Fighting", "Magery", "Meditation", "Mining", "Musicianship", "Parrying", "Peacemaking", "Poisoning", "Provocation", "Remove Trap", "Resisting Spells", "Snooping", "Spirit Speak", "Stealing", "Swordsmanship", "Tactics", "Tailoring", "Taste Identification", "Tinkering", "Tracking", "Veterinary", "Wrestling" }));

        javax.swing.GroupLayout skillsPanelLayout = new javax.swing.GroupLayout(skillsPanel);
        skillsPanel.setLayout(skillsPanelLayout);
        skillsPanelLayout.setHorizontalGroup(
            skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        skillsPanelLayout.setVerticalGroup(
            skillsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Stats"));

        intLabel.setText("Int");

        intSlider.setMinimum(25);
        intSlider.setValue(25);
        intSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        intSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intSliderStateChanged(evt);
            }
        });

        intTextField.setText("25");
        intTextField.setDisabledTextColor(java.awt.Color.black);
        intTextField.setEnabled(false);

        strLabel.setText("Str");

        strSlider.setMinimum(25);
        strSlider.setValue(25);
        strSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                strSliderStateChanged(evt);
            }
        });

        strTextField.setText("25");
        strTextField.setDisabledTextColor(java.awt.Color.black);
        strTextField.setEnabled(false);

        dexLabel.setText("Dex");

        dexSlider.setMinimum(25);
        dexSlider.setValue(25);
        dexSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dexSliderStateChanged(evt);
            }
        });

        dexTextField.setText("25");
        dexTextField.setDisabledTextColor(java.awt.Color.black);
        dexTextField.setEnabled(false);

        toogleInt.setText("L");
        toogleInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleIntActionPerformed(evt);
            }
        });

        toogleStr.setText("L");
        toogleStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleStrActionPerformed(evt);
            }
        });

        toogleDex.setText("L");
        toogleDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toogleDexActionPerformed(evt);
            }
        });

        totalLabel.setText("Total: 225");

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(intSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(intTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toogleInt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(strSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(strTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toogleStr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(dexSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dexTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toogleDex, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intLabel)
                            .addComponent(strLabel)
                            .addComponent(dexLabel)
                            .addComponent(totalLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(intTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toogleInt))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(intLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(strTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toogleStr))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(strLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(strSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dexTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(toogleDex))
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addComponent(dexLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dexSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(totalLabel)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        loadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        loadMenuItem.setText("Load Template");
        fileMenu.add(loadMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        saveMenuItem.setText("Save Template");
        fileMenu.add(saveMenuItem);
        fileMenu.add(separatorMenuItems);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        deleteMenuItem.setText("Delete Template");
        fileMenu.add(deleteMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText("Exit");
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        whoMenuItem.setText("whoami");
        helpMenu.add(whoMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(skillsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(skillsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intSliderStateChanged
        if (isMaxed()) {
            intSlider.setMaximum(intSlider.getValue());
        } else {
            intSlider.setMaximum(100);
        }
        intTextField.setText(String.valueOf(intSlider.getValue()));
        currentTotalStats = intSlider.getValue() + strSlider.getValue() + dexSlider.getValue();
        setTotal(currentTotalStats);


    }//GEN-LAST:event_intSliderStateChanged

    private void strSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_strSliderStateChanged
        if (isMaxed()) {
            strSlider.setMaximum(strSlider.getValue());
        } else {
            strSlider.setMaximum(100);
        }
        strTextField.setText(String.valueOf(strSlider.getValue()));
        currentTotalStats = intSlider.getValue() + strSlider.getValue() + dexSlider.getValue();
        setTotal(currentTotalStats);

    }//GEN-LAST:event_strSliderStateChanged

    private void dexSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dexSliderStateChanged
        if (isMaxed()) {
            dexSlider.setMaximum(dexSlider.getValue());
        } else {
            dexSlider.setMaximum(100);
        }
        dexTextField.setText(String.valueOf(dexSlider.getValue()));
        currentTotalStats = intSlider.getValue() + strSlider.getValue() + dexSlider.getValue();
        setTotal(currentTotalStats);
    }//GEN-LAST:event_dexSliderStateChanged

    private void toogleIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleIntActionPerformed
        if (toogleInt.isSelected()){
            intSlider.setEnabled(false);
        }else{
            intSlider.setEnabled(true);
        }
    }//GEN-LAST:event_toogleIntActionPerformed

    private void toogleStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleStrActionPerformed
        if (toogleStr.isSelected()){
            strSlider.setEnabled(false);
        }else{
            strSlider.setEnabled(true);
        }
    }//GEN-LAST:event_toogleStrActionPerformed

    private void toogleDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toogleDexActionPerformed
        // TODO add your handling code here:
        if (toogleDex.isSelected()){
            dexSlider.setEnabled(false);
        }else{
            dexSlider.setEnabled(true);
        }
    }//GEN-LAST:event_toogleDexActionPerformed
    private void setTotal(int total){
        if (total > 225){
            totalLabel.setForeground(Color.red);
        }else{
            totalLabel.setForeground(Color.black);
        }
        totalLabel.setText("Total: " + String.valueOf(total));
    }
    private boolean isMaxed(){
        return MAX_STATS <= currentTotalStats;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combo3;
    private javax.swing.JComboBox<String> combo4;
    private javax.swing.JComboBox<String> combo5;
    private javax.swing.JComboBox<String> combo6;
    private javax.swing.JComboBox<String> combo7;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JLabel dexLabel;
    private javax.swing.JSlider dexSlider;
    private javax.swing.JTextField dexTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel intLabel;
    private javax.swing.JSlider intSlider;
    private javax.swing.JTextField intTextField;
    private javax.swing.JMenuItem loadMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel namePanel;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JPopupMenu.Separator separatorMenuItems;
    private javax.swing.JPanel skillsPanel;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JLabel strLabel;
    private javax.swing.JSlider strSlider;
    private javax.swing.JTextField strTextField;
    private javax.swing.JLabel templateLabel;
    private javax.swing.JTextField templateTextField;
    private javax.swing.JToggleButton toogleDex;
    private javax.swing.JToggleButton toogleInt;
    private javax.swing.JToggleButton toogleStr;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JMenuItem whoMenuItem;
    // End of variables declaration//GEN-END:variables
}
